### ISSUE TITLE
Where Should We Fork?

### ISSUE THREAD

**Issue by Magnitus-** [opentffoundation/manifesto#598]
I recently started a fork from tag v1.5.5 of Terraform.

However, there are a fair number of commits after 1.5.5 release, but before the license change that are not included: https://github.com/Magnitus-/opentf/compare/main...hashicorp:terraform:main

Roughly, there are almost 300 commits between the v1.5.5 tag and the license change. 

We could:
- Go from the latest possible commit
- Go from tag v1.5.5

I like going from tag v1.5.5 because we know it is reasonably stable and then we can cherry-pick any of the later commits as needed even though it might be a little more work to reconcile afterwards.

Any thoughts?

**Comment by cube2222** [comment]
@Magnitus- I'm not sure if you've seen, but Cory from Massdriver has sent you an email 2 days ago.

Anyway, please reach out to me on kubam@spacelift.io from an email on which you are reachable.

I can't tell too much here, but I'd recommend not working on this until further news from our side (sorry, can't reveal more in public yet).

**Comment by pdecat** [comment]
Tag v1.5.6 was just published and still under MPL 2.0, as is the `v1.5` from which it was tagged: https://github.com/hashicorp/terraform/tree/v1.5

**Comment by Magnitus-** [comment]
This question is addressed in the official announcement. I will close this issue.
