### ISSUE TITLE
Add fallback request for a shortened Change Date

### ISSUE THREAD

**Issue by voxpelli** [opentffoundation/manifesto#665]
The BUSL (unlike the SSPL license which Elastic and MongoDB switched to) will eventually convert to an unrestricted OSS _Change License_  which in Hashicorp's case is MPL2, but it's up to the licensor to say after how long time.

The creator of the BUSL, MariaDb, writes this in their FAQ (emphasis mine):

> [Q: How far in the future is the recommended Change Date?](https://mariadb.com/bsl-faq-adopting/#future)
> 
> A: Picking the right Change Date depends on how rapidly the software is changing. Bear in mind that, regardless of the Change Date, the Change License will take effect on the fourth anniversary of the first publicly available distribution of software under the BSL. For most software, the recommendation is four years, which is the BSL’s default position. **For rapidly developing software, an earlier Change Date may help encourage community contributions.**

So, if Hashicorp won't switch back to an OSS license and there will be a fork of Terraform, then you should still lobby Hashicorp to make the Change Date shorter than [the current 4 years that they are targeting](https://www.hashicorp.com/license-faq#usage-limitations) (which happens to be the max allowed bu BUSL)

A shorter Change Date, like eg. a 6-12 month one, would make Hashicorp's Terraform act more like a "downstream" fork of your "upstream" one and you can pull back changes after the 6-12 months has passed. That would ensure that your community version and the Hashicorp proprietary version would stay more in sync, which would be good for Hashicorp as well, as they can then benefit from contributions to the community version as well.

If Hashicorp choose to stick by 4 years as the Change Date, then you should demand a justification for that other than "that's the default of the BUSL license". In practice a 4 years Change Date for Terraform is far too long to be useful in practice and far longer than Hashicorp can justify.

**Comment by SebastianStadil** [comment]
We'd love it if they did! However they haven't bothered to respond to the community, so we don't think an additional ask will change anything.

Thus we've started work on OpenTF! We're excited to share our work with you soon, see here: https://github.com/opentffoundation/roadmap/milestones
