### ISSUE TITLE
Update announcement.html

### ISSUE THREAD

**Issue by crypto-br** [opentffoundation/manifesto#702]
Updating the amount of stars in the repository for 3.8k

**Comment by VanshSutariya** [comment]
I'd like to work on this issue ; can you please assign me this  issue or I can just raised the PR ?

**Comment by Magnitus-** [comment]
> I'd like to work on this issue ; can you please assign me this issue or I can just raised the PR ?

I think you could probably just open a PR. It seems like a very small change.

Maybe phase it in such a way that it is clear that change was added after the post war originally written (ie, "(Aug 27 edit: Now 4k stars)"

**Comment by VanshSutariya** [comment]
ok ,I will change it to  4k

**Comment by AuracleTech** [comment]
I updated it to 6.3k

**Comment by mednbiba** [comment]
Refactored for 7.5k Stars

**Comment by emito-k** [comment]
haha best of luck! 1 star from me!

**Comment by DicsyDel** [comment]
Announcement is a point in time page and represents state of things at a time of the announcement. Dynamic stars counter is already available on our manifesto page. Hope it makes sense.
