### ISSUE TITLE
Dynamically Change Github stars count in `announcement.html`

### ISSUE THREAD

**Issue by ShatilKhan** [opentffoundation/manifesto#770]
Since `Fireship.io`'s Video about the OpenTF movement tonight, `OpenTF` has been getting `Github Stars`   by the second!
 So I thought instead of changing it manually, we can just dynamically change the star count using some basic `JS scripts`.

**Comment by ShatilKhan** [comment]
I added a PR that changed the Github star count on this line in `anouncement.html` :
`the manifesto already has over 9.2k stars`
My script automatically updated the star count.

**Comment by DicsyDel** [comment]
Announcement is a point in time page and represents state of things at a time of the announcement. Dynamic stars counter is already available on our manifesto page. Hope it makes sense.

**Comment by ShatilKhan** [comment]
Thanks for the clarification @DicsyDel 
Will keep that in mind.
