### ISSUE TITLE
Why so much fear-mongering in your manifesto instead of trying to clarify what the actual change is?

### ISSUE THREAD

**Issue by johncf** [opentffoundation/manifesto#919]
> Overnight, tens of thousands of businesses, ranging from one-person shops to the Fortune 500 woke up to a new reality where the underpinnings of their infrastructure suddenly became a potential legal risk. The BUSL and the additional use grant written by the HashiCorp team are vague. Now, every company, vendor, and developer using Terraform has to wonder whether what they are doing could be construed as competitive with HashiCorp's offerings. The FAQ provides some solace for end-customers and systems integrators today, but even if you might be in the clear now, how can you build confidence that your usage won't violate the license terms in the future?

The goal of Hashicorp is clear -- prevent 3rd party providers from offering their own products and charge for it without Hashicorp gaining anything. In fact, you can even use Terraform to build and host a product that's competitive to Terraform, using Terraform v1.6+! As long as what you're building and commercially offering doesn't share Terraform v1.6+ source code. This is clarified in their [FAQ](https://www.hashicorp.com/license-faq#competitive-product-bsl-coverage):

> The BSL license does not prevent developers from using our tools to build competing products. For example, if someone built a product competitive with Vault, it would be permissible to deploy that product with Terraform. Similarly, if someone built a competitive product to Terraform, they could use Vault to secure it. What the BSL license would not allow is hosting or embedding Terraform in order to compete with Terraform, or hosting or embedding Vault to compete with Vault.

This means, their license change to BSL 1.1 actually doesn't affect 99% of Terraform users in any way. But the way you've worded it (esp. in the paragraph I quoted above) seems to be aimed at causing undue alarm among your readers. Firstly, even though you point out that Hashicorp's "FAQ provides some solace", you've conveniently not linked to the said FAQ, which would have actually helped a reader to become more informed.

Please make an effort to provide a more balanced perspective on the situation, and help your readers be informed on the subject by encouraging them to read Hashicorp's original announcement and its associated FAQ.

**Comment by SebastianStadil** [comment]
Thanks for sharing your views!

Whether or not you are right about Hashi's intentions, OpenTF is going to be amazing. It's going to be community first, impartial, open source, and once again, amazing.

PS: This is probably better as a discussion rather than an issue, so I'm locking the conversation and welcome you to keep the conversation going there.
